### PR TITLE
Update AAT and perftest to have fact and fact-admin

### PR DESCRIPTION
**Pull request by linusnorton**
Add fact-admin DNS

### CODE REVIEW

**Comment by timja** [comment]
sandbox service principal expired, let me nudge someone

**Comment by timja** [comment]
fixed that

**Review by timja — COMMENTED** [review]
you'll need an afdverify record in public dns for this as well

https://github.com/hmcts/azure-public-dns/blob/master/environments/staging/aat.yml#L154-L156

**Comment by linusnorton** [comment]
@timja https://github.com/hmcts/azure-public-dns/pull/340

**Review by timja — APPROVED** [review]

**Pull request merged**
